//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Net.Security;

namespace Digst.OioIdws.WscJavaExample.HelloWorldProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/contract/HelloWorld", ConfigurationName="HelloWorldProxy.HelloWorldPortType")]
    public interface HelloWorldPortType {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.example.org/schema/HelloWorld) of message HelloWorldRequest does not match the default value (http://www.example.org/contract/HelloWorld)
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=ProtectionLevel.Sign, Action="http://www.example.org/contract/HelloWorld/HelloWorldPortType/HelloWorldRequest", ReplyAction="http://www.example.org/contract/HelloWorld/HelloWorldPortType/HelloWorldResponse")]
        Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldResponse HelloWorld(Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel = ProtectionLevel.Sign, Action = "http://www.example.org/contract/HelloWorld/HelloWorldPortType/HelloWorldRequest", ReplyAction="http://www.example.org/contract/HelloWorld/HelloWorldPortType/HelloWorldResponse")]
        System.Threading.Tasks.Task<Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldResponse> HelloWorldAsync(Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld", WrapperNamespace="http://www.example.org/schema/HelloWorld", IsWrapped=true)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string name;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldResponse", WrapperNamespace="http://www.example.org/schema/HelloWorld", IsWrapped=true)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string response;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(string response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWorldPortTypeChannel : Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldPortTypeClient : System.ServiceModel.ClientBase<Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldPortType>, Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldPortType {
        
        public HelloWorldPortTypeClient() {
        }
        
        public HelloWorldPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HelloWorldPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HelloWorldPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldResponse Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldPortType.HelloWorld(Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string name) {
            Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldRequest inValue = new Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldRequest();
            inValue.name = name;
            Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldResponse retVal = ((Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldPortType)(this)).HelloWorld(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldResponse> Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldPortType.HelloWorldAsync(Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldResponse> HelloWorldAsync(string name) {
            Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldRequest inValue = new Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldRequest();
            inValue.name = name;
            return ((Digst.OioIdws.WscJavaExample.HelloWorldProxy.HelloWorldPortType)(this)).HelloWorldAsync(inValue);
        }
    }
}
