version: "2.0"
services:
  mysql:
    image: mysql:latest
    ports:
     - 6666:3306
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_PASSWORD: "Test1234"
      MYSQL_USER: "sds"
      MYSQL_DATABASE: "sts"
    volumes:
      - ./db:/var/lib/mysql

  sts:
    image: sdsxua/sts
    environment:
      MYSQL_CONNECTION: "jdbc:mysql://mysql:3306/sts"
      MYSQL_PASSWORD: "Test1234"
      MYSQL_USER: "sds"
    ports:
      - 8181:8181

  simple-idp:
    image: sdsxua/idp
    ports:
      - 8443:8443
