using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

// General Information about an assembly is controlled through the following
// set of attributes. Change these attribute values to modify the information
// associated with an assembly.
[assembly: AssemblyTitle("Digst.OioIdws.Wsp.Wsdl")]
[assembly: AssemblyDescription("Digst.OioIdws.Wsp.Wsdl is a .Net-based reference implementation of the OIOIDWS 1.1 profile. The Toolkit can be used by services to customize the WSDL generated by .NET WCF in order to make it easier to consume by other technologies (ex: Java)")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Digitaliseringsstyrelsen")]
[assembly: AssemblyProduct("Digst.OioIdws.Wsp.Wsdl")]
[assembly: AssemblyCopyright("Copyright ©  2018")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

// Setting ComVisible to false makes the types in this assembly not visible
// to COM components.  If you need to access a type in this assembly from
// COM, set the ComVisible attribute to true on that type.
[assembly: ComVisible(false)]

// The following GUID is for the ID of the typelib if this project is exposed to COM
[assembly: Guid("4535c5e6-a44e-4952-8edb-ba207b16b8a8")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version
//      Build Number
//      Revision
//
// You can specify all the values or you can default the Build and Revision Numbers
// by using the '*' as shown below:
//[assembly: AssemblyVersion("1.0.*")]
//[assembly: AssemblyVersion("1.0.0.0")]
//[assembly: AssemblyFileVersion("1.0.0.0")]
