//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

namespace Digst.OioIdws.Wsp.BasicPrivilegeProfile
{
// 
// This source code was auto-generated by xsd, Version=4.6.81.0.
// 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://itst.dk/oiosaml/basic_privilege_profile")]
    [XmlRoot("PrivilegeList", Namespace="http://itst.dk/oiosaml/basic_privilege_profile", IsNullable=false)]
    public partial class PrivilegeListType {
    
        private PrivilegeGroupType[] privilegeGroupField;
    
        /// <remarks/>
        [XmlElement("PrivilegeGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public PrivilegeGroupType[] PrivilegeGroup {
            get {
                return this.privilegeGroupField;
            }
            set {
                this.privilegeGroupField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.6.81.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [XmlType(Namespace="http://itst.dk/oiosaml/basic_privilege_profile")]
    public partial class PrivilegeGroupType {
    
        private string[] privilegeField;
    
        private string scopeField;
    
        /// <remarks/>
        [XmlElement("Privilege", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] Privilege {
            get {
                return this.privilegeField;
            }
            set {
                this.privilegeField = value;
            }
        }
    
        /// <remarks/>
        [XmlAttribute()]
        public string Scope {
            get {
                return this.scopeField;
            }
            set {
                this.scopeField = value;
            }
        }
    }
}