//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.example.org/contract/HelloWorld", ConfigurationName="DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldPortType")]
    public interface HelloWorldPortType
    {
        
        // CODEGEN: Generating message contract since the wrapper namespace (http://www.example.org/schema/HelloWorld) of message HelloWorldRequest does not match the default value (http://www.example.org/contract/HelloWorld)
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://www.example.org/contract/HelloWorld/HelloWorldPortType/HelloWorldRequest", ReplyAction="*")]
        DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldResponse HelloWorld(DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(ProtectionLevel=System.Net.Security.ProtectionLevel.Sign, Action="http://www.example.org/contract/HelloWorld/HelloWorldPortType/HelloWorldRequest", ReplyAction="*")]
        System.Threading.Tasks.Task<DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldResponse> HelloWorldAsync(DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorld", WrapperNamespace="http://www.example.org/schema/HelloWorld", IsWrapped=true)]
    public partial class HelloWorldRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string name;
        
        public HelloWorldRequest()
        {
        }
        
        public HelloWorldRequest(string name)
        {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="HelloWorldResponse", WrapperNamespace="http://www.example.org/schema/HelloWorld", IsWrapped=true)]
    public partial class HelloWorldResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string response;
        
        public HelloWorldResponse()
        {
        }
        
        public HelloWorldResponse(string response)
        {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HelloWorldPortTypeChannel : DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HelloWorldPortTypeClient : System.ServiceModel.ClientBase<DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldPortType>, DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldPortType
    {
        
        public HelloWorldPortTypeClient()
        {
        }
        
        public HelloWorldPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public HelloWorldPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HelloWorldPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public HelloWorldPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldResponse DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldPortType.HelloWorld(DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldRequest request)
        {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld(string name)
        {
            DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldRequest inValue = new DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldRequest();
            inValue.name = name;
            DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldResponse retVal = ((DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldPortType)(this)).HelloWorld(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldResponse> DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldPortType.HelloWorldAsync(DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldRequest request)
        {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldResponse> HelloWorldAsync(string name)
        {
            DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldRequest inValue = new DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldRequest();
            inValue.name = name;
            return ((DK.Gov.Oio.Idws.IntegrationTests.JavaHelloWorldProxy.HelloWorldPortType)(this)).HelloWorldAsync(inValue);
        }
    }
}
