//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Digst.OioIdws.TestWebServiceConsumer.WebServiceProducerProxy {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://nemlog-in.dk/securitytokenservices", ConfigurationName="WebServiceProducerProxy.ISecurityTokenServiceMessageEcho")]
    public interface ISecurityTokenServiceMessageEcho {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nemlog-in.dk/securitytokenservices/echo/Issue", ReplyAction="http://nemlog-in.dk/securitytokenservices/echo/IssueReply")]
        System.ServiceModel.Channels.Message IssueToken(System.ServiceModel.Channels.Message request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://nemlog-in.dk/securitytokenservices/echo/Issue", ReplyAction="http://nemlog-in.dk/securitytokenservices/echo/IssueReply")]
        System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> IssueTokenAsync(System.ServiceModel.Channels.Message request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurityTokenServiceMessageEchoChannel : Digst.OioIdws.TestWebServiceConsumer.WebServiceProducerProxy.ISecurityTokenServiceMessageEcho, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityTokenServiceMessageEchoClient : System.ServiceModel.ClientBase<Digst.OioIdws.TestWebServiceConsumer.WebServiceProducerProxy.ISecurityTokenServiceMessageEcho>, Digst.OioIdws.TestWebServiceConsumer.WebServiceProducerProxy.ISecurityTokenServiceMessageEcho {
        
        public SecurityTokenServiceMessageEchoClient() {
        }
        
        public SecurityTokenServiceMessageEchoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityTokenServiceMessageEchoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityTokenServiceMessageEchoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityTokenServiceMessageEchoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Channels.Message IssueToken(System.ServiceModel.Channels.Message request) {
            return base.Channel.IssueToken(request);
        }
        
        public System.Threading.Tasks.Task<System.ServiceModel.Channels.Message> IssueTokenAsync(System.ServiceModel.Channels.Message request) {
            return base.Channel.IssueTokenAsync(request);
        }
    }
}
